### ISSUE TITLE
I even added the deepl api and it doesn't want to work

### ISSUE THREAD

**Issue by Elabrax** [PingLaggerYT/TranslateX#6]
[21:43:52 ERROR] [Minecraft]: Exception when ElAbraX attempted to tab complete t setlang
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/t setlang ' in plugin TranslateX v0.4-BETA
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.tabCompleteCommand(CraftServerMixin.java:2058) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.tabComplete(CraftServerMixin.java:2030) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:60) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.1.8.jar%23110!/:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:599) ~[brigadier-1.1.8.jar%23110!/:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[brigadier-1.1.8.jar%23110!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7741_(ServerPlayNetHandlerMixin.java:520) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.m_5797_(ServerboundCommandSuggestionPacket.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.m_5797_(ServerboundCommandSuggestionPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.network.protocol.PacketUtils.mdb1aec8$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.deepl.api.Translator.getSourceLanguages()" because the return value of "nl.rubixstudios.translate.translate.TranslateController.getTranslator()" is null
        at nl.rubixstudios.translate.command.TranslatorCommand.onTabComplete(TranslatorCommand.java:154) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1]
        ... 25 more
-----------------------------------------------------------------------------------------------------------------------------------------
org.bukkit.event.EventException: null
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1] {re:mixin,re:classloading}
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1] {re:mixin,re:classloading,re:mixin}
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23210!/:arclight-1.20.1-1.0.4-fd335c1] {re:mixin,re:classloading,re:mixin}
at net.minecraft.server.players.PlayerList.eject$bck000$arclight$playerJoin(PlayerListMixin.java:1085) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.PlayerListMixin,pl:mixin:A}
at net.minecraft.server.players.PlayerList.m_11261_(PlayerListMixin.java:203) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerListMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.PlayerListMixin,pl:mixin:A}
at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginNetHandlerMixin.java:607) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerLoginNetHandlerMixin,pl:mixin:A}
at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginNetHandlerMixin.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerLoginNetHandlerMixin,pl:mixin:A}
at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:classloading,re:mixin}
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin,re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "com.deepl.api.Translator.getSourceLanguages()" because the return value of "nl.rubixstudios.translate.translate.TranslateController.getTranslator()" is null
at nl.rubixstudios.translate.translate.listener.PlayerJoinEventListener.onJoin(PlayerJoinEventListener.java:52) ~[?:?] {}

**Comment by Elabrax** [comment]
Hola?

**Comment by Djorr** [comment]
Hi, issue has been solved. You can download the latest version on spigot:
https://www.spigotmc.org/resources/translatex-ai-translator-1-7-1-20-2.112949/history
